# Generated by Django 5.0.6 on 2024-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='image',
            field=models.ImageField(default=2, upload_to='image'),
            preserve_default=False,
        ),
    ]
